permissions = [
    "core:default",
    # "core:path:default",
    # "core:event:default",
    "core:event:allow-listen",
    # "core:window:default",
    "core:window:allow-create",
    "core:window:allow-close",
    "updater:allow-check",
    # "core:updater:default",
    "process:allow-restart",
    "core:window:allow-set-title",
    "core:window:allow-destroy",
    "core:webview:allow-create-webview-window",
    "core:webview:allow-create-webview",
    "core:webview:allow-webview-close",
    # "core:webview:default",
    # "core:app:default",
    "core:resources:default",
    # "core:menu:default",
    # "core:tray:default",
]
"$schema" = "./schemas/desktop-schema.toml"
identifier = "main-capability"
description = "Capability for the main window"
windows = ["main", "wallet-connect"]
